# Generated by Django 3.2.9 on 2021-12-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpersonalinfo',
            old_name='bloodType',
            new_name='blood_type',
        ),
        migrations.RemoveField(
            model_name='userpersonalinfo',
            name='address',
        ),
    ]
